[tool.black]
line-length = 132
target-version = ['py37', 'py38']
include = '(\.py$)'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | todd_linux/todd/dist
)/
'''

[tool.isort]
profile = "black"
# from https://black.readthedocs.io/en/stable/compatible_configs.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 132
