name: Build Todd Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Update environment
        run: |
          sudo apt install -y bash binutils bison bzip2 coreutils diffutils findutils gawk gcc g++ grep gzip m4 make patch perl python3 sed tar texinfo xz-utils
          sudo rm /bin/sh
          sudo ln -s bash /bin/sh
          sudo rm /usr/bin/yacc
          sudo ln -s bison /usr/bin/yacc
          sudo rm /usr/bin/awk
          sudo ln -s gawk /usr/bin/awk

      - name: Create LFS Environment
        run: |
          mkdir ${{github.workspace}}/lfs
          python3 ${{github.workspace}}/host/sign_lfs.py ${{github.workspace}}/lfs

      - name: Build
        run: |
          python3 ${{github.workspace}}/host/setup.py ${{github.workspace}}/lfs

